language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8

script:
  - sbt coverage coverageReport

after_success:
  - export CODECOV_TOKEN="71b9196a-f071-49b6-82d9-8ca1fca8c797"
  - bash <(curl -s https://codecov.io/bash)
